# Values for fiware/keyrock Helm Chart
#
# Chart values file:
# ref: https://github.com/FIWARE/helm-charts/blob/main/charts/keyrock/values.yaml
#

## deployment specific configuration
deployment:
  ## configuration of the image to be used
  image:
    ## keyrock image name
    ## ref: https://hub.docker.com/r/fiware/idm
    repository: fiware/idm
    ## tag of the image to be used
    tag: i4trust-rc7
    ## specification of the image pull policy
    pullPolicy: IfNotPresent
    
## Set either an ingress or openshift route for making Keyrock externally available
##
## openshift specific route definition. Will not work on plain k8s
route:
  ## -- should the deployment create openshift routes
  enabled: false   
## ingress configuration
ingress:
  ## should there be an ingress to connect keyrock with the public internet
  enabled: false

## database configuration for keyrock
db:
  ## host of the database to be used (K8s internal service hostname)
  host: mysql.provider.svc.cluster.local
  ## user for connecting the database
  user: root
  ## password for connecting the database (MySQL root password)
  password: <mysql-root-password>

## admin configuration for accessing keyrock
admin:
  ## username of the initial keyrock admin
  user: admin
  ## password of the initial admin
  password: <keyrock-admin-password>
  ## email address of the admin user
  email: my@mail.org

## Theme configuration for Keyrock
# This is optional and showcases how to add a theme for the Keyrock UI. This setup is
# using the Packet Delivery Co. theme of the demo setup.
theme:
  ## -- Enable theme
    enabled: true
    ## -- Name of the theme
    name: i4trust-happypets
    ## -- Size of PVCs to be created
    size: 1Gi
    ## Image which holds the theme files
    image: i4trust/keyrock-theme-happypets:0.0.1
    ## -- specification of the image pull policy
    imagePullPolicy: Always
    ## Path to the source theme files inside the container
    sourceTheme: /themes/i4trust-happypets
    ## Path to the source image files inside the container
    sourceImg: /img/i4trust-happypets
    ## Optional: Path to the source favicon directory inside the container
    sourceFavicon: /favicon
    ## Mount path for the source theme files
    mountTheme: /opt/fiware-idm/themes/i4trust-happypets
    ## Mount path for the source image files
    mountImg: /opt/fiware-idm/public/img/i4trust-happypets
    ## Mount path for the source favicon
    mountFavicon: /opt/fiware-idm/public/favicon.ico

## a list of additional env vars to be set, check the keyrock docu for all available options
## ref: https://fiware-idm.readthedocs.io/en/latest/installation_and_administration_guide/environment_variables/index.html
additionalEnvVars:
  # Title to be displayed on default theme UI
  - name: IDM_TITLE
    value: My Company IDP
  # Name of the database to be created within the MySQL
  - name: IDM_DB_NAME
    value: idm
  # Initialize and seed database on startup
  - name: IDM_DB_SEED
    value: "true"
  # Maximum header size of internal web server
  - name: IDM_SERVER_MAX_HEADER_SIZE
    value: "32768"
  # URL of iSHARE Satellite
  - name: IDM_PR_URL
    value: https://scheme.isharetest.net
  # Token endpoint of iSHARE Satellite
  - name: IDM_PR_TOKEN_ENDPOINT
    value: https://scheme.isharetest.net/connect/token
  # Parties endpoint of iSHARE Satellite
  - name: IDM_PR_PARTIES_ENDPOINT
    value: https://scheme.isharetest.net/parties
  # EORI of iSHARE Satellite
  - name: IDM_PR_ID
    value: EU.EORI.NL000000000
  # EORI of data service consuming company
  - name: IDM_PR_CLIENT_ID
    value: EU.EORI.NLHAPPYPETS
  # URL of external Authorisation Registry (put 'internal' if internal AR should be used)
  - name: IDM_AR_URL
    value: https://ar.isharetest.net
  # EORI of external Authorisation Registry
  - name: IDM_AR_ID
    value: EU.EORI.NL000000004
  # Token endpoint of external Authorisation Registry
  - name: IDM_AR_TOKEN_ENDPOINT
    value: https://ar.isharetest.net/connect/token
  # Delegation endpoint of external Authorisation Registry
  - name: IDM_AR_DELEGATION_ENDPOINT
    value: https://ar.isharetest.net/delegation
  # Private key of data service consuming company
  - name: IDM_PR_CLIENT_KEY
    value: |
      -----BEGIN PRIVATE KEY-----
      <Put key here>
      -----END PRIVATE KEY-----
  # Certificate chain of data service consuming company
  - name: IDM_PR_CLIENT_CRT
    value: |
      -----BEGIN CERTIFICATE-----
      <Put certificates here>
      -----END CERTIFICATE-----
      
