# Values for bitnami/mongodb Helm Chart
#
# Chart values file:
# ref: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
#

image:
  ## Bitnami MongoDB image name
  ##
  repository: bitnami/mongodb
  ## Bitnami MongoDB image tag
  ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
  ##
  tag: 4.4.13
  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

## MongoDB architecture. Allowed values: standalone or replicaset
##
architecture: standalone

## Use StatefulSet instead of Deployment when deploying standalone
##
useStatefulSet: false

## MongoDB Authentication parameters
##
auth:
  ## Enable authentication
  ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
  ##
  enabled: true
  ## MongoDB root password
  ## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  rootPassword: "<root-password>"

## initdb scripts
## Specify dictionary of scripts to be run at first boot
##
## !!! Only required when using API Umbrella !!!
## This creates the required database and user for API Umbrella.
## Make sure to set the DB user configuration and database
## for the API Umbrella deployment.
##
## If you omit the creation of database and user during deployment, make sure
## to create this database and user afterwards manually before proceeding with the
## API Umbrella deployment.
##
initdbScripts:
  init_db.js: |
    // Setup DB for API Umbrella
    db = db.getSiblingDB('api_umbrella');
    db.createUser(
    {
      user: "api_umbrella",
      pwd: "api-umbrella-password",
      roles: [
        {
          role: "readWrite",
          db: "api_umbrella"
        }
      ]
    });

## MongoDB pods' Security Context. (might be necessary on OpenShift)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
#podSecurityContext:
#  enabled: false

## MongoDB containers' Security Context (main and metrics container). (might be necessary on OpenShift)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
#containerSecurityContext:
#  enabled: false
