# Default values for activation-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## deployment specific configuration
deployment:
  ## configuration of the image to be used
  image:
    # -- image name
    # ref: https://hub.docker.com/r/i4trust/activation-service
    repository: i4trust/activation-service
    # -- tag of the image to be used
    tag: 1.1.1
  
## ingress configuration
ingress:
  # -- should there be an ingress to connect the activation service with the public internet
  enabled: true
  # -- annotations to be added to the ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  # -- all hosts to be provided
  hosts:
    - host: activation-service.domain.org
      paths:
        - /
  # -- configure the ingress' tls
  tls:
    - secretName: activation-service-prod-tls
      hosts: 
        - activation-service.domain.org

## Debug output
debug:
  enabled: false
      
## Activation Service configuration
config:
  # Client configuration
  client:
    # Client ID (EORI)
    id: "EU.EORI.NLPACKETDEL"
    # Client key (PEM private key)
    key: |
      -----BEGIN PRIVATE KEY-----
      <Put private key here>
      -----END PRIVATE KEY-----
    # Client certificate (PEM certificate chain)
    crt: |
      -----BEGIN CERTIFICATE-----
      <Put certificate chain here>
      -----END CERTIFICATE-----
  # Configuration of express web server
  express:
    # Port (Internal port of the express web server)
    port: 7000
  # Configuration of SQLite database
  db:
    # Source (":memory:" or file e.g. "db.sqlite" for persistence)
    source: ":memory:"    
  # Configuration of authorisation registry
  ar:
    # Endpoint for token request
    token: "https://ar.isharetest.net/connect/token"
    # Endpoint for create policy requests
    policy: "https://ar.isharetest.net/policy"
    # Endpoint for delegation requests
    delegation: "https://ar.isharetest.net/delegation"
    # EORI of AR
    id: "EU.EORI.NL000000004"
    # Disable SSL verification
    rejectUnauthorized: false
