# Values for fiware/business-api-ecosystem Helm Chart
#
# Chart values file:
# ref: https://github.com/FIWARE/helm-charts/blob/main/charts/business-api-ecosystem/values.yaml
#


## Marketplace OAuth and IdM configuration
##
oauth:
  # URL of the FIWARE IDM dedicated to the BAE used for user authentication (administrative access)
  # Should match the host of the Ingress or Route of the Keyrock instance
  server: https://keyrock.domain.org
  # OAuth2 Client ID of the BAE application within Keyrock
  clientId: <CLIENT-ID>
  # OAuth2 Client Secret of the BAE application within Keyrock
  clientSecret: <CLIENT-SECRET>
  

## External URL used to access the BAE frontend (logic proxy)
## Should match the host of the Ingress or Route of the Logic Proxy
##
externalUrl: https://marketplace.domain.org


## Configuration for biz-ecosystem-apis component
##
bizEcosystemApis:
  ## database configuration for APIs (MySQL)
  db:
    ## host of the database to be used (K8s internal service hostname)
    host: mysql.marketplace.svc.cluster.local
    ## password for connecting the database (MySQL root password)
    password: <mysql-root-password>

  ## port that the APIs container uses
  port: 8080

  ## Service account (might be necessary on OpenShift)
  #serviceAccount:
  #  create: false
  #  name: <account-name>

  ## Security context (might be necessary on OpenShift)
  #securityContext:
    ## -- specifies the user UID
  #  runAsUser: 0
    ## -- specifies the group GID
  #  runAsGroup: 0

    
## Configuration for biz-ecosystem-rss component
##
bizEcosystemRss:
  ## database configuration for RSS (MySQL)
  db:
    ## host of the database to be used (K8s internal service hostname)
    host: mysql.marketplace.svc.cluster.local
    ## URL connection string of the database to be used (leave the port and DB name RSS unchanged)
    url: jdbc:mysql://mysql.marketplace.svc.cluster.local:3306/RSS
    ## password for connecting the database (MySQL root password)
    password: <mysql-root-password>

  ## port that the RSS container uses
  port: 8080

  ## Service account (might be necessary on OpenShift)
  #serviceAccount:
  #  create: false
  #  name: <account-name>

  ## Security context (might be necessary on OpenShift)
  #securityContext:
    ## -- specifies the user UID
  #  runAsUser: 0
    ## -- specifies the group GID
  #  runAsGroup: 0


## Configuration for biz-ecosystem-charging-backend component
##
bizEcosystemChargingBackend:
  ## -- deployment specific configuration
  deployment:
    ## -- configuration of the image to be used
    image:
      ## -- BAE Charging backend image name
      ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-charging-backend
      repository: fiware/biz-ecosystem-charging-backend
      ## -- tag of the image to be used
      tag: v7.9.0-rc1

  ## -- PVC configuration for charging backend plugins
  ## Enable to allow loading plugins from PVC.
  ## Some plugins require access to IDM, for this Keyrock IDM admin credentials need to be provided.
  plugins:
    ## -- Enable the PVC for plugins storage
    enabled: true
    ## -- IDM Admin username
    idmUser: admin
    ## -- IDM Admin password
    idmPassword: <keyrock-admin-password>

  ## database configuration for Charging backend (MongoDB)
  db:
    ## host of the database to be used (K8s internal service hostname)
    host: mongodb.marketplace.svc.cluster.local
    ## Database name for connecting the database
    database: charging_db
    ## username for connecting the database
    user: charging
    ## password for connecting the database (MongoDB password of user charging)
    password: charging-password

  ## port that the charging backend container uses
  port: 8006

  ## payment configuration
  payment:
    ## method: paypal or None
    method: None

  ## Paypal Oauth2 configuration (if payment.method == paypal)
  #paypal:
    ## Paypal Client-ID
  #  clientId: <CLIENT-ID>
    ## Paypal Client-Secret
  #  clientSecret: <CLIENT-SECRET>

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    enabled: true
    identifier: "EU.EORI.NLMARKETPLA"
    key: |
      -----BEGIN PRIVATE KEY-----
      <put private key here>
      -----END PRIVATE KEY-----
    cert: |
      -----BEGIN CERTIFICATE-----
      <put certificate chain here>
      -----END CERTIFICATE-----

  ## Service account (might be necessary on OpenShift)
  #serviceAccount:
  #  create: false
  #  name: <account-name>

  ## Security context (might be necessary on OpenShift)
  #securityContext:
    ## -- specifies the user UID
  #  runAsUser: 0
    ## -- specifies the group GID
  #  runAsGroup: 0



## Configuration for biz-ecosystem-logic-proxy component
##
bizEcosystemLogicProxy:
  ## Set either an ingress or openshift route for making the Marketplace UI externally available
  ##
  ## openshift specific route definition. Will not work on plain k8s
  route:
    ## -- should the deployment create openshift routes
    enabled: false
  ## ingress configuration
  ingress:
    ## -- should there be an ingress to connect the logic proxy with the public internet
    enabled: false

  ## -- deployment specific configuration
  deployment:
    ## -- configuration of the image to be used
    image:
      ## -- BAE Logic Proxy image name
      ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-logic-proxy
      repository: fiware/biz-ecosystem-logic-proxy
      ## -- tag of the image to be used
      tag: v7.9.0-rc2


  ## database configuration for Logic Proxy (MongoDB)
  db:
    # host of the database to be used (K8s internal service hostname)
    host: mongodb.marketplace.svc.cluster.local
    # Database name for connecting the database
    database: belp_db
    # username for connecting the database
    user: belp
    # password for connecting the database (MongoDB password of user charging)
    password: belp-password

  ## -- elasticsearch configuration
  elastic:
    ## -- indexing engine of logic proxy
    engine: elasticsearch
    ## -- URL of elasticsearch service
    url: elasticsearch-master.marketplace.svc.cluster.local:9200
    ## -- API version of elasticsearch
    version: 7.5

  ## Deployment in development or in production
  nodeEnvironment: production

  ## port that the logic proxy container uses
  port: 8004

  ## -- Custom theme configuration
  theme:
    ## -- Enable theme
    enabled: true
    ## -- Name of the theme
    name: i4trust
    ## -- Size of PVC to be created
    size: 4Gi
    ## Image which holds the theme files
    image: i4trust/bae-i4trust-theme:v0.0.3
    # -- specification of the image pull policy
    imagePullPolicy: Always
    ## Path to the source theme files inside the container
    #  Files will be copied to /themes/{{name}} with the PVC mounted at /themes
    sourcePath: /bae-i4trust-theme

  ## -- Configuration for external IDPs
  ## Below is an example for adding the IDPs of the reference example with their respective
  ## EORI IDs. This list needs to be changed according to the participants of the
  ## data space.
  externalIdp:
    # -- Enable usage of external IDPs
    enabled: true
    # -- JSON string with external IDP configurations
    # "[{name: 'NAME', server: 'URL', idpId: 'ID'}, ...]"
    config: |
      [{"name": "Packet Delivery Company", "server": "https://idp-pdc.i4trust.fiware.io", "idpId": "EU.EORI.NLPACKETDEL"},
       {"name": "Happy Pets Inc.", "server": "https://idp-happypets.i4trust.fiware.io", "idpId": "EU.EORI.NLHAPPYPETS"},
       {"name": "No Cheaper Inc.", "server": "https://idp-nocheaper.i4trust.fiware.io", "idpId": "EU.EORI.NLNOCHEAPER"}]

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    enabled: true
    identifier: "EU.EORI.NLMARKETPLA"
    key: |
      -----BEGIN PRIVATE KEY-----
      <put private key here>
      -----END PRIVATE KEY-----
    cert: |
      -----BEGIN CERTIFICATE-----
      <put certificate chain here>
      -----END CERTIFICATE-----
      
  ## Service account (might be necessary on OpenShift)
  #serviceAccount:
  #  create: false
  #  name: <account-name>

  ## Security context (might be necessary on OpenShift)
  #securityContext:
    ## -- specifies the user UID
  #  runAsUser: 0
    ## -- specifies the group GID
  #  runAsGroup: 0
