mongodb:
  image:
    tag: 4.4.2-debian-10-r0

  auth:
    enabled: false
  architecture: standalone

  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

  persistence: 
    size: 1Gi
